# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d455eae20ce7ad178287f5b10a2bbae445bae2790c20dcf82224968cbf5ceed9cddb86fdcc1baa4d5949ab75127b8d2c25d8233def64adc00f9186db745c231f

test:
  secret_key_base: 18b8a6b88e95ad1b62a8c9bba69bf6692a95390a7c26da4a7962f3e6fb8fd7a20f8cde6ce3f26a5a73469d1beec1bf745675eccc517e3c885a039b6fb18d3d21

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
